### ISSUE TITLE
Mannschaft nachträglich bearbeiten

### ISSUE THREAD

**Issue by michburger** [Bruno17/fbuch#16]
Feature Request: Man sieht beim Nachbearbeiten den Fahrtenbuch-Eintrags die Mannschaftsmitglieder nicht mehr (und man kann sie auch nicht löschen).

**Comment by Bruno17** [comment]
Die neu gebaute Ansicht wird diese Möglichkeit beinhalten.
https://github.com/Bruno17/fbuch/blob/aafafe826ed9ad9af0d975e73e06ec72644bd448/assets/components/fbuch/quasar/views/fahrtenbuch/entryform-view.html#L89
