### ISSUE TITLE
Tooltips auf Fahrt-Knöpfen

### ISSUE THREAD

**Issue by michburger** [Bruno17/fbuch#17]
Die Symbole der Knöpfe auf der Fahrt erklären die Funktionalität nicht komplett, ein Tooltip mit mehr Auskunft würde helfen.

**Comment by Bruno17** [comment]
Schwierig an mobilen bzw. Touchgeräten.
Die neu gebaute Ansicht wird auf jeden Fall vollständige Aufklappmenüs mit beschreibenden Texten haben.
