### ISSUE TITLE
php 8.0: empty age in lists yields error

### ISSUE THREAD

**Issue by michburger** [Bruno17/fbuch#19]

**Comment by Bruno17** [comment]
@michburger 
Dies wurde mit #22 erledigt, richtig?

**Comment by michburger** [comment]
Lieber Bruno,das ist korrekt. Hoffe, dass Du mit dieser Alternative leben kannst: es wird der Altersdurchschnitt der Ruderer mit Geburtsdatum genommen.Eine Alternative wäre, eine Fehlermeldung zu senden.Viele Grüße Michael Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Bruno17 ***@***.***> Datum: 28.11.22  10:16  (GMT+01:00) An: Bruno17/fbuch ***@***.***> Cc: michburger ***@***.***>, Mention ***@***.***> Betreff: Re: [Bruno17/fbuch] php 8.0: empty age in lists yields error (Issue #19) 
@michburger
Dies wurde mit #22 erledigt, richtig?

**Comment by Bruno17** [comment]
das sollte passen. Hatte ich ja schon gemerged. Dann kann ich das Issue schließen.
